services:
  - type: web
    name: midai
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate --noinput
      mkdir -p staticfiles
      python manage.py collectstatic --noinput
    startCommand: gunicorn MidAI.wsgi:application