services:
  - type: web
    name: midai
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic
    startCommand: gunicorn MidAI.wsgi:application