services:
  - type: web
    name: midai
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      # Collecte les statics pour prod, --noinput pour éviter les prompts
      python manage.py collectstatic --noinput
    startCommand: |
      # Gunicorn avec binding sur l'adresse par défaut de Render
      gunicorn MidAI.wsgi:application --bind 0.0.0.0:$PORT
